/*
 * Open APi
 *
 * This is a sample server. 
 *
 * API version: 1.0.0
 * Contact: email@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	BlogApiService := openapi.NewBlogApiService()
	BlogApiController := openapi.NewBlogApiController(BlogApiService)

	CommentApiService := openapi.NewCommentApiService()
	CommentApiController := openapi.NewCommentApiController(CommentApiService)

	PostApiService := openapi.NewPostApiService()
	PostApiController := openapi.NewPostApiController(PostApiService)

	UserApiService := openapi.NewUserApiService()
	UserApiController := openapi.NewUserApiController(UserApiService)

	router := openapi.NewRouter(BlogApiController, CommentApiController, PostApiController, UserApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
