"""
    GComments

    APIs for creating and managing comments   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@comments.app
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="GComments",
    author="API Support",
    author_email="support@comments.app",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "GComments"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description="""\
    APIs for creating and managing comments   # noqa: E501
    """
)
