/*
 * Open APi
 * This is a sample server. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: email@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.Media;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Comment
 */
public class CommentTest {
    private final Comment model = new Comment();

    /**
     * Model tests for Comment
     */
    @Test
    public void testComment() {
        // TODO: test Comment
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'postId'
     */
    @Test
    public void postIdTest() {
        // TODO: test postId
    }

    /**
     * Test the property 'blogId'
     */
    @Test
    public void blogIdTest() {
        // TODO: test blogId
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'authorDisplayName'
     */
    @Test
    public void authorDisplayNameTest() {
        // TODO: test authorDisplayName
    }

    /**
     * Test the property 'createdTimestamp'
     */
    @Test
    public void createdTimestampTest() {
        // TODO: test createdTimestamp
    }

    /**
     * Test the property 'modifiedTimestamp'
     */
    @Test
    public void modifiedTimestampTest() {
        // TODO: test modifiedTimestamp
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'downvoteCount'
     */
    @Test
    public void downvoteCountTest() {
        // TODO: test downvoteCount
    }

    /**
     * Test the property 'upvoteCount'
     */
    @Test
    public void upvoteCountTest() {
        // TODO: test upvoteCount
    }

    /**
     * Test the property 'media'
     */
    @Test
    public void mediaTest() {
        // TODO: test media
    }

}
