/*
 * Open APi
 * This is a sample server. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: email@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VerificationStatus
 */
public class VerificationStatusTest {
    private final VerificationStatus model = new VerificationStatus();

    /**
     * Model tests for VerificationStatus
     */
    @Test
    public void testVerificationStatus() {
        // TODO: test VerificationStatus
    }

    /**
     * Test the property 'isVerified'
     */
    @Test
    public void isVerifiedTest() {
        // TODO: test isVerified
    }

    /**
     * Test the property 'verificationTimestamp'
     */
    @Test
    public void verificationTimestampTest() {
        // TODO: test verificationTimestamp
    }

    /**
     * Test the property 'verificationMethod'
     */
    @Test
    public void verificationMethodTest() {
        // TODO: test verificationMethod
    }

}
