=begin
#Open APi

#This is a sample server. 

The version of the OpenAPI document: 1.0.0
Contact: email@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::BlogApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BlogApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::BlogApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BlogApi' do
    it 'should create an instance of BlogApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::BlogApi)
    end
  end

  # unit tests for add_blog
  # Add a new blog
  # @param [Hash] opts the optional parameters
  # @option opts [Blog] :blog Blog object that needs to be added
  # @return [nil]
  describe 'add_blog test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_blog
  # Deletes a blog
  # @param blog_id Blog id to delete
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key 
  # @return [nil]
  describe 'delete_blog test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_blog_by_id
  # Find blog by ID
  # Returns a single blog
  # @param blog_id ID of blog to return
  # @param [Hash] opts the optional parameters
  # @return [Blog]
  describe 'get_blog_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_blog
  # Update an existing blog
  # @param [Hash] opts the optional parameters
  # @option opts [Blog] :blog Blog object that needs to be added
  # @return [nil]
  describe 'update_blog test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_blog_with_form
  # Updates a blog with form data
  # @param blog_id ID of blog that needs to be updated
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [String] :url 
  # @option opts [String] :auth_token 
  # @option opts [String] :comment_status 
  # @return [nil]
  describe 'update_blog_with_form test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
