"""
    Open APi

    This is a sample server.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: email@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.post import Post


class TestPost(unittest.TestCase):
    """Post unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPost(self):
        """Test Post"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Post()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
