/**
 * Open APi
 * This is a sample server. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: email@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApi);
  }
}(this, function(expect, OpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApi.Comment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Comment', function() {
    it('should create an instance of Comment', function() {
      // uncomment below and update the code to test Comment
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be.a(OpenApi.Comment);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property postId (base name: "postId")', function() {
      // uncomment below and update the code to test the property postId
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property blogId (base name: "blogId")', function() {
      // uncomment below and update the code to test the property blogId
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property parentId (base name: "parentId")', function() {
      // uncomment below and update the code to test the property parentId
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property authorDisplayName (base name: "authorDisplayName")', function() {
      // uncomment below and update the code to test the property authorDisplayName
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property createdTimestamp (base name: "created_timestamp")', function() {
      // uncomment below and update the code to test the property createdTimestamp
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property modifiedTimestamp (base name: "modified_timestamp")', function() {
      // uncomment below and update the code to test the property modifiedTimestamp
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property downvoteCount (base name: "downvoteCount")', function() {
      // uncomment below and update the code to test the property downvoteCount
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property upvoteCount (base name: "upvoteCount")', function() {
      // uncomment below and update the code to test the property upvoteCount
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

    it('should have the property media (base name: "media")', function() {
      // uncomment below and update the code to test the property media
      //var instance = new OpenApi.Comment();
      //expect(instance).to.be();
    });

  });

}));
