/**
 * Open APi
 * This is a sample server. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: email@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApi);
  }
}(this, function(expect, OpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApi.VerificationStatus();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VerificationStatus', function() {
    it('should create an instance of VerificationStatus', function() {
      // uncomment below and update the code to test VerificationStatus
      //var instance = new OpenApi.VerificationStatus();
      //expect(instance).to.be.a(OpenApi.VerificationStatus);
    });

    it('should have the property isVerified (base name: "isVerified")', function() {
      // uncomment below and update the code to test the property isVerified
      //var instance = new OpenApi.VerificationStatus();
      //expect(instance).to.be();
    });

    it('should have the property verificationTimestamp (base name: "verificationTimestamp")', function() {
      // uncomment below and update the code to test the property verificationTimestamp
      //var instance = new OpenApi.VerificationStatus();
      //expect(instance).to.be();
    });

    it('should have the property verificationMethod (base name: "verificationMethod")', function() {
      // uncomment below and update the code to test the property verificationMethod
      //var instance = new OpenApi.VerificationStatus();
      //expect(instance).to.be();
    });

  });

}));
