/**
 * GComments
 * APIs for creating and managing comments 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@comments.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VerificationStatus model module.
 * @module model/VerificationStatus
 * @version 1.0.0
 */
class VerificationStatus {
    /**
     * Constructs a new <code>VerificationStatus</code>.
     * @alias module:model/VerificationStatus
     */
    constructor() { 
        
        VerificationStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VerificationStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VerificationStatus} obj Optional instance to populate.
     * @return {module:model/VerificationStatus} The populated <code>VerificationStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VerificationStatus();

            if (data.hasOwnProperty('isVerified')) {
                obj['isVerified'] = ApiClient.convertToType(data['isVerified'], 'Boolean');
            }
            if (data.hasOwnProperty('verificationTimestamp')) {
                obj['verificationTimestamp'] = ApiClient.convertToType(data['verificationTimestamp'], 'Date');
            }
            if (data.hasOwnProperty('verificationMethod')) {
                obj['verificationMethod'] = ApiClient.convertToType(data['verificationMethod'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} isVerified
 */
VerificationStatus.prototype['isVerified'] = undefined;

/**
 * @member {Date} verificationTimestamp
 */
VerificationStatus.prototype['verificationTimestamp'] = undefined;

/**
 * @member {String} verificationMethod
 */
VerificationStatus.prototype['verificationMethod'] = undefined;






export default VerificationStatus;

