/**
 * GComments
 * APIs for creating and managing comments 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@comments.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package app.gcomments.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class Blog implements Serializable {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("authToken")
  private String authToken = null;
  public enum CommentStatusEnum {
     Disabled,  RequireReview,  AutomateReview, 
  };
  @SerializedName("commentStatus")
  private CommentStatusEnum commentStatus = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getAuthToken() {
    return authToken;
  }
  public void setAuthToken(String authToken) {
    this.authToken = authToken;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CommentStatusEnum getCommentStatus() {
    return commentStatus;
  }
  public void setCommentStatus(CommentStatusEnum commentStatus) {
    this.commentStatus = commentStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Blog blog = (Blog) o;
    return (this.id == null ? blog.id == null : this.id.equals(blog.id)) &&
        (this.name == null ? blog.name == null : this.name.equals(blog.name)) &&
        (this.url == null ? blog.url == null : this.url.equals(blog.url)) &&
        (this.authToken == null ? blog.authToken == null : this.authToken.equals(blog.authToken)) &&
        (this.commentStatus == null ? blog.commentStatus == null : this.commentStatus.equals(blog.commentStatus));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.authToken == null ? 0: this.authToken.hashCode());
    result = 31 * result + (this.commentStatus == null ? 0: this.commentStatus.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Blog {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  authToken: ").append(authToken).append("\n");
    sb.append("  commentStatus: ").append(commentStatus).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
