/**
 * Open APi
 * This is a sample server. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: email@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package app.gcomments.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

@ApiModel(description = "")
public class Post implements Serializable {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("excerpt")
  private String excerpt = null;
  @SerializedName("content")
  private String content = null;
  public enum CommentStatusEnum {
     Disabled,  RequireReview,  AutomateReview, 
  };
  @SerializedName("commentStatus")
  private CommentStatusEnum commentStatus = null;
  @SerializedName("postType")
  private String postType = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExcerpt() {
    return excerpt;
  }
  public void setExcerpt(String excerpt) {
    this.excerpt = excerpt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getContent() {
    return content;
  }
  public void setContent(String content) {
    this.content = content;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public CommentStatusEnum getCommentStatus() {
    return commentStatus;
  }
  public void setCommentStatus(CommentStatusEnum commentStatus) {
    this.commentStatus = commentStatus;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPostType() {
    return postType;
  }
  public void setPostType(String postType) {
    this.postType = postType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Post post = (Post) o;
    return (this.id == null ? post.id == null : this.id.equals(post.id)) &&
        (this.title == null ? post.title == null : this.title.equals(post.title)) &&
        (this.url == null ? post.url == null : this.url.equals(post.url)) &&
        (this.excerpt == null ? post.excerpt == null : this.excerpt.equals(post.excerpt)) &&
        (this.content == null ? post.content == null : this.content.equals(post.content)) &&
        (this.commentStatus == null ? post.commentStatus == null : this.commentStatus.equals(post.commentStatus)) &&
        (this.postType == null ? post.postType == null : this.postType.equals(post.postType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.excerpt == null ? 0: this.excerpt.hashCode());
    result = 31 * result + (this.content == null ? 0: this.content.hashCode());
    result = 31 * result + (this.commentStatus == null ? 0: this.commentStatus.hashCode());
    result = 31 * result + (this.postType == null ? 0: this.postType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Post {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  excerpt: ").append(excerpt).append("\n");
    sb.append("  content: ").append(content).append("\n");
    sb.append("  commentStatus: ").append(commentStatus).append("\n");
    sb.append("  postType: ").append(postType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
