/**
 * GComments
 * APIs for creating and managing comments 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@comments.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Post {
    'id'?: string;
    'title'?: string;
    'url'?: string;
    'excerpt'?: string;
    'content'?: string;
    'commentStatus'?: Post.CommentStatusEnum;
    'postType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "excerpt",
            "baseName": "excerpt",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "commentStatus",
            "baseName": "commentStatus",
            "type": "Post.CommentStatusEnum"
        },
        {
            "name": "postType",
            "baseName": "postType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Post.attributeTypeMap;
    }
}

export namespace Post {
    export enum CommentStatusEnum {
        Disabled = <any> 'Disabled',
        RequireReview = <any> 'RequireReview',
        AutomateReview = <any> 'AutomateReview'
    }
}
