openapi: 3.0.0
info:
  version: "1.0.0"
  title: GComments
  description: |
    APIs for creating and managing comments
  termsOfService: 'https://comments.app/tos'
  contact:
    name: API Support
    url: https://comments.app/support
    email: support@comments.app
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:8080'
tags:
  - name: comment
    description: Everything about your Comments
  - name: post
    description: Everything about your Posts
  - name: user
    description: Everything about your Users
  - name: blog
    description: Everything about your Blogs
paths:
  /comment:
    $ref: "./paths/comment.yaml"
  '/comment/{commentId}':
    $ref: "./paths/commentid.yaml"
  /post:
    $ref: "./paths/post.yaml"     
  '/post/{postId}':
    $ref: "./paths/postid.yaml"
  /blog:
    $ref: "./paths/blog.yaml"
  '/blog/{blogId}':
    $ref: "./paths/blogid.yaml"
  /user:
    $ref: "./paths/user.yaml"
  /user/login:
    $ref: "./paths/login.yaml"
  /user/logout:
    $ref: "./paths/logout.yaml"
  '/user/{username}':
    $ref: "./paths/username.yaml"
components:
  schemas:
    Comment:
      $ref: './models/Comment.yaml'
    Media:
      $ref: './models/Media.yaml'
    Post:
      $ref: "./models/Post.yaml"
    User:
      $ref: "./models/User.yaml"
    Role:
      $ref: "./models/Role.yaml"
    VerificationStatus:
      $ref: "./models/VerificationStatus.yaml"
    Blog:
      $ref: "./models/Blog.yaml"
  requestBodies:
    Comment:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Comment'
        application/xml:
          schema:
            $ref: '#/components/schemas/Comment'
      description: Comment object that needs to be added
      required: true
    Post:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Post'
        application/xml:
          schema:
            $ref: '#/components/schemas/Post'
      description: Post object that needs to be added
    Blog:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Blog'
        application/xml:
          schema:
            $ref: '#/components/schemas/Blog'
      description: Blog object that needs to be added
  securitySchemes:
    cm_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
          scopes:
            'write': modify 
            'read': read
    api_key:
      type: apiKey
      name: api_key
      in: header