/*
 * GComments
 *
 * APIs for creating and managing comments 
 *
 * API version: 1.0.0
 * Contact: support@comments.app
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gcomments

import (
	"context"
	"net/http"
	"errors"
)

// PostApiService is a service that implements the logic for the PostApiServicer
// This service should implement the business logic for every endpoint for the PostApi API.
// Include any external packages or services that will be required by this service.
type PostApiService struct {
}

// NewPostApiService creates a default api service
func NewPostApiService() PostApiServicer {
	return &PostApiService{}
}

// AddPost - Add a new post
func (s *PostApiService) AddPost(ctx context.Context, post Post) (ImplResponse, error) {
	// TODO - update AddPost with the required logic for this service method.
	// Add api_post_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	//return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddPost method not implemented")
}

// DeletePost - Deletes a post
func (s *PostApiService) DeletePost(ctx context.Context, postId string, apiKey string) (ImplResponse, error) {
	// TODO - update DeletePost with the required logic for this service method.
	// Add api_post_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeletePost method not implemented")
}

// GetPostById - Find post by ID
func (s *PostApiService) GetPostById(ctx context.Context, postId string) (ImplResponse, error) {
	// TODO - update GetPostById with the required logic for this service method.
	// Add api_post_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Post{}) or use other options such as http.Ok ...
	//return Response(200, Post{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetPostById method not implemented")
}

// UpdatePost - Update an existing post
func (s *PostApiService) UpdatePost(ctx context.Context, post Post) (ImplResponse, error) {
	// TODO - update UpdatePost with the required logic for this service method.
	// Add api_post_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	//return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdatePost method not implemented")
}

// UpdatePostWithForm - Updates a post with form data
func (s *PostApiService) UpdatePostWithForm(ctx context.Context, postId string, title string, url string, excerpt string, content string, commentStatus string, postType string) (ImplResponse, error) {
	// TODO - update UpdatePostWithForm with the required logic for this service method.
	// Add api_post_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	//return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdatePostWithForm method not implemented")
}
