/**
 * GComments
 * APIs for creating and managing comments 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@comments.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Media } from './media';


/**
 * A user-generated comment.
 */
export interface Comment { 
    /**
     * The ID of this comment.
     */
    id?: string;
    /**
     * The ID of the author.
     */
    userId?: string;
    /**
     * The ID of the post hosting this comment.
     */
    postId?: string;
    blogId?: string;
    parentId?: string;
    authorDisplayName?: string;
    created_timestamp?: string;
    modified_timestamp?: string;
    content?: string;
    status?: Comment.StatusEnum;
    downvoteCount?: number;
    upvoteCount?: number;
    media?: Media;
}
export namespace Comment {
    export type StatusEnum = 'Draft' | 'InReview' | 'Flagged' | 'Published' | 'Deleted';
    export const StatusEnum = {
        Draft: 'Draft' as StatusEnum,
        InReview: 'InReview' as StatusEnum,
        Flagged: 'Flagged' as StatusEnum,
        Published: 'Published' as StatusEnum,
        Deleted: 'Deleted' as StatusEnum
    };
}


