/**
 * Open APi
 * This is a sample server. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: email@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Post { 
    id?: string;
    title?: string;
    url?: string;
    excerpt?: string;
    content?: string;
    commentStatus?: Post.CommentStatusEnum;
    postType?: string;
}
export namespace Post {
    export type CommentStatusEnum = 'Disabled' | 'RequireReview' | 'AutomateReview';
    export const CommentStatusEnum = {
        Disabled: 'Disabled' as CommentStatusEnum,
        RequireReview: 'RequireReview' as CommentStatusEnum,
        AutomateReview: 'AutomateReview' as CommentStatusEnum
    };
}


