/**
 * GComments
 * APIs for creating and managing comments 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@comments.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { VerificationStatus } from './verificationStatus';
import { Blog } from './blog';


export interface User { 
    id?: string;
    username?: string;
    password?: string;
    niceName?: string;
    avatarUrl?: string;
    displayName?: string;
    email?: string;
    role?: Role;
    blogs?: Array<Blog>;
    verificationStatus?: VerificationStatus;
}

